version: '2'

services:
  elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
#    networks:
#      - elk
  logstash:
    build: logstash/
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000/udp"
      - "12201:12201/udp"
#    networks:
#      - elk
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
#    networks:
#      - elk

#networks:
#  elk:
#    driver: bridge

# sample usage:
#  docker run -d --name httpd -p 80:80 --log-driver=gelf --log-opt gelf-address=udp://192.168.99.100:12201 --log-opt tag="fe" httpd
